services:
  - type: web
    name: portfolio
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/bin/java      # Change this if you are using a different version of Java
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free
    autoDeploy: true
