services:
  - type: web
    name: portfolio
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/portfolio-1.0-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free
    autoDeploy: true
