services:
  - type: web
    name: portfolio
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/portfolio-1.0-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64  # Change this if you are using a different version of Java
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free
    autoDeploy: true
